namespace Clinic.Application.Clinical;

/// <summary>An ICD-10 code with its Persian and English names.</summary>
public sealed record Icd10Code(string Code, string Fa, string En);

/// <summary>
/// The WHO ICD-10 codes a family-medicine and acupuncture clinic uses most, so that the doctor can find a code by
/// typing a word of the diagnosis in Persian or English. Codes not listed can still be typed by hand.
/// </summary>
public static class Icd10Catalog
{
    public static readonly IReadOnlyList<Icd10Code> All =
    [
        // Endocrine, nutrition and metabolism
        new("E66.0", "چاقی ناشی از کالری اضافه", "Obesity due to excess calories"),
        new("E66.8", "چاقی (سایر انواع)", "Other obesity"),
        new("E66.9", "چاقی، نامشخص", "Obesity, unspecified"),
        new("R63.5", "افزایش وزن غیرطبیعی", "Abnormal weight gain"),
        new("R63.4", "کاهش وزن غیرطبیعی", "Abnormal weight loss"),
        new("R63.0", "بی‌اشتهایی", "Anorexia (loss of appetite)"),
        new("E44.1", "سوءتغذیه خفیف", "Mild protein-energy malnutrition"),
        new("E11.9", "دیابت نوع ۲ بدون عارضه", "Type 2 diabetes mellitus without complications"),
        new("E10.9", "دیابت نوع ۱ بدون عارضه", "Type 1 diabetes mellitus without complications"),
        new("R73.0", "اختلال تست تحمل گلوکز (پیش‌دیابت)", "Abnormal glucose tolerance test (prediabetes)"),
        new("E78.0", "افزایش کلسترول خون", "Pure hypercholesterolaemia"),
        new("E78.1", "افزایش تری‌گلیسرید خون", "Pure hyperglyceridaemia"),
        new("E78.5", "چربی خون بالا، نامشخص", "Hyperlipidaemia, unspecified"),
        new("E03.9", "کم‌کاری تیروئید", "Hypothyroidism, unspecified"),
        new("E05.9", "پرکاری تیروئید", "Thyrotoxicosis, unspecified"),
        new("E04.9", "گواتر غیرسمی", "Nontoxic goitre, unspecified"),
        new("E28.2", "سندرم تخمدان پلی‌کیستیک", "Polycystic ovarian syndrome"),
        new("E55.9", "کمبود ویتامین D", "Vitamin D deficiency, unspecified"),
        new("E53.8", "کمبود ویتامین B12 و سایر ویتامین‌های گروه B", "Deficiency of other specified B group vitamins"),
        new("E61.1", "کمبود آهن", "Iron deficiency"),
        new("E88.8", "سندرم متابولیک و سایر اختلالات متابولیک", "Other specified metabolic disorders (metabolic syndrome)"),
        new("E87.6", "کمبود پتاسیم", "Hypokalaemia"),
        new("E83.5", "اختلال متابولیسم کلسیم", "Disorders of calcium metabolism"),

        // Blood
        new("D50.9", "کم‌خونی فقر آهن", "Iron deficiency anaemia, unspecified"),
        new("D51.9", "کم‌خونی کمبود ویتامین B12", "Vitamin B12 deficiency anaemia, unspecified"),
        new("D64.9", "کم‌خونی، نامشخص", "Anaemia, unspecified"),
        new("D56.1", "تالاسمی بتا", "Beta thalassaemia"),

        // Mental and behavioural
        new("F41.1", "اختلال اضطراب فراگیر", "Generalized anxiety disorder"),
        new("F41.0", "اختلال پانیک (حملات هراس)", "Panic disorder"),
        new("F41.2", "اضطراب و افسردگی مختلط", "Mixed anxiety and depressive disorder"),
        new("F41.9", "اضطراب، نامشخص", "Anxiety disorder, unspecified"),
        new("F32.0", "افسردگی خفیف", "Mild depressive episode"),
        new("F32.1", "افسردگی متوسط", "Moderate depressive episode"),
        new("F32.9", "افسردگی، نامشخص", "Depressive episode, unspecified"),
        new("F33.9", "افسردگی عودکننده", "Recurrent depressive disorder, unspecified"),
        new("F43.0", "واکنش حاد به استرس", "Acute stress reaction"),
        new("F43.1", "اختلال استرس پس از سانحه", "Post-traumatic stress disorder"),
        new("F43.2", "اختلال سازگاری", "Adjustment disorders"),
        new("F42.9", "وسواس فکری-عملی", "Obsessive-compulsive disorder, unspecified"),
        new("F45.9", "اختلال جسمانی‌شکل (شکایات جسمی روانی)", "Somatoform disorder, unspecified"),
        new("F48.0", "خستگی عصبی (نوراستنی)", "Neurasthenia"),
        new("F51.0", "بی‌خوابی غیرعضوی", "Nonorganic insomnia"),
        new("F50.2", "پرخوری عصبی (بولیمیا)", "Bulimia nervosa"),
        new("F50.0", "بی‌اشتهایی عصبی", "Anorexia nervosa"),
        new("F50.9", "اختلال خوردن، نامشخص", "Eating disorder, unspecified"),
        new("F17.2", "وابستگی به نیکوتین (سیگار)", "Mental and behavioural disorders due to use of tobacco: dependence syndrome"),
        new("F10.2", "وابستگی به الکل", "Alcohol dependence syndrome"),
        new("F11.2", "وابستگی به مواد افیونی", "Opioid dependence syndrome"),
        new("F90.0", "اختلال بیش‌فعالی و کمبود توجه", "Disturbance of activity and attention (ADHD)"),
        new("F52.2", "اختلال نعوظ و برانگیختگی جنسی", "Failure of genital response"),
        new("F52.0", "کاهش میل جنسی", "Lack or loss of sexual desire"),

        // Nervous system
        new("G43.9", "میگرن", "Migraine, unspecified"),
        new("G43.0", "میگرن بدون اورا", "Migraine without aura"),
        new("G43.1", "میگرن با اورا", "Migraine with aura"),
        new("G44.2", "سردرد تنشی", "Tension-type headache"),
        new("G44.0", "سردرد خوشه‌ای", "Cluster headache syndrome"),
        new("R51", "سردرد", "Headache"),
        new("G47.0", "بی‌خوابی", "Disorders of initiating and maintaining sleep (insomnia)"),
        new("G47.3", "آپنه خواب", "Sleep apnoea"),
        new("G47.9", "اختلال خواب، نامشخص", "Sleep disorder, unspecified"),
        new("G51.0", "فلج بل (فلج عصب صورت)", "Bell's palsy"),
        new("G50.0", "نورالژی تری‌ژمینال", "Trigeminal neuralgia"),
        new("G56.0", "سندرم تونل کارپ", "Carpal tunnel syndrome"),
        new("G57.0", "آسیب عصب سیاتیک", "Lesion of sciatic nerve"),
        new("G62.9", "نوروپاتی محیطی", "Polyneuropathy, unspecified"),
        new("E11.4", "نوروپاتی دیابتی", "Type 2 diabetes mellitus with neurological complications"),
        new("G25.8", "سندرم پای بی‌قرار و سایر اختلالات حرکتی", "Other specified extrapyramidal and movement disorders (restless legs)"),
        new("G35", "مولتیپل اسکلروزیس (ام‌اس)", "Multiple sclerosis"),
        new("G20", "بیماری پارکینسون", "Parkinson's disease"),
        new("G40.9", "صرع", "Epilepsy, unspecified"),
        new("I63.9", "سکته مغزی (انفارکتوس مغزی)", "Cerebral infarction, unspecified"),
        new("I69.4", "عوارض پس از سکته مغزی", "Sequelae of stroke"),
        new("G81.9", "همی‌پلژی", "Hemiplegia, unspecified"),
        new("R42", "سرگیجه", "Dizziness and giddiness"),
        new("H81.1", "سرگیجه وضعیتی خوش‌خیم", "Benign paroxysmal vertigo"),
        new("H93.1", "وزوز گوش", "Tinnitus"),
        new("H91.9", "کاهش شنوایی", "Hearing loss, unspecified"),
        new("H10.9", "ورم ملتحمه", "Conjunctivitis, unspecified"),
        new("H04.1", "خشکی چشم", "Other disorders of lacrimal gland (dry eye)"),

        // Circulatory
        new("I10", "فشار خون بالا", "Essential (primary) hypertension"),
        new("I95.9", "فشار خون پایین", "Hypotension, unspecified"),
        new("I25.9", "بیماری ایسکمیک قلب", "Chronic ischaemic heart disease, unspecified"),
        new("I20.9", "آنژین صدری", "Angina pectoris, unspecified"),
        new("I49.9", "آریتمی قلبی", "Cardiac arrhythmia, unspecified"),
        new("R00.2", "تپش قلب", "Palpitations"),
        new("I50.9", "نارسایی قلب", "Heart failure, unspecified"),
        new("I83.9", "واریس پا", "Varicose veins of lower extremities without ulcer or inflammation"),
        new("I84.9", "بواسیر (هموروئید)", "Haemorrhoids, unspecified"),
        new("I73.0", "سندرم رینود", "Raynaud's syndrome"),
        new("I87.2", "نارسایی وریدی", "Venous insufficiency (chronic)(peripheral)"),
        new("R60.0", "ادم موضعی (ورم)", "Localized oedema"),

        // Respiratory
        new("J00", "سرماخوردگی", "Acute nasopharyngitis (common cold)"),
        new("J01.9", "سینوزیت حاد", "Acute sinusitis, unspecified"),
        new("J32.9", "سینوزیت مزمن", "Chronic sinusitis, unspecified"),
        new("J30.4", "رینیت آلرژیک", "Allergic rhinitis, unspecified"),
        new("J30.1", "آلرژی فصلی (تب یونجه)", "Allergic rhinitis due to pollen"),
        new("J02.9", "گلودرد (فارنژیت حاد)", "Acute pharyngitis, unspecified"),
        new("J03.9", "التهاب لوزه", "Acute tonsillitis, unspecified"),
        new("J06.9", "عفونت حاد تنفسی فوقانی", "Acute upper respiratory infection, unspecified"),
        new("J11.1", "آنفلوانزا", "Influenza with other respiratory manifestations, virus not identified"),
        new("J20.9", "برونشیت حاد", "Acute bronchitis, unspecified"),
        new("J45.9", "آسم", "Asthma, unspecified"),
        new("J44.9", "بیماری انسدادی مزمن ریه (COPD)", "Chronic obstructive pulmonary disease, unspecified"),
        new("R05", "سرفه", "Cough"),
        new("R06.0", "تنگی نفس", "Dyspnoea"),
        new("J18.9", "ذات‌الریه (پنومونی)", "Pneumonia, unspecified"),
        new("U07.1", "کووید-۱۹", "COVID-19, virus identified"),

        // Digestive
        new("K21.9", "ریفلاکس معده به مری", "Gastro-oesophageal reflux disease without oesophagitis"),
        new("K29.7", "گاستریت (التهاب معده)", "Gastritis, unspecified"),
        new("K30", "سوءهاضمه (دیسپپسی)", "Dyspepsia"),
        new("K25.9", "زخم معده", "Gastric ulcer, unspecified"),
        new("K27.9", "زخم گوارشی", "Peptic ulcer, site unspecified"),
        new("K58.9", "سندرم روده تحریک‌پذیر", "Irritable bowel syndrome without diarrhoea"),
        new("K58.0", "روده تحریک‌پذیر همراه اسهال", "Irritable bowel syndrome with diarrhoea"),
        new("K59.0", "یبوست", "Constipation"),
        new("K59.1", "اسهال عملکردی", "Functional diarrhoea"),
        new("A09", "گاستروانتریت و اسهال عفونی", "Diarrhoea and gastroenteritis of presumed infectious origin"),
        new("R14", "نفخ", "Flatulence and related conditions (bloating)"),
        new("R11", "تهوع و استفراغ", "Nausea and vomiting"),
        new("R10.4", "درد شکم", "Other and unspecified abdominal pain"),
        new("K76.0", "کبد چرب", "Fatty (change of) liver, not elsewhere classified"),
        new("K80.2", "سنگ کیسه صفرا", "Calculus of gallbladder without cholecystitis"),
        new("K50.9", "بیماری کرون", "Crohn's disease, unspecified"),
        new("K51.9", "کولیت اولسراتیو", "Ulcerative colitis, unspecified"),
        new("K60.2", "شقاق مقعد (فیشر)", "Anal fissure, unspecified"),
        new("K12.0", "آفت دهان", "Recurrent oral aphthae"),
        new("K07.6", "اختلال مفصل گیجگاهی-فکی", "Temporomandibular joint disorders"),
        new("K90.0", "بیماری سلیاک", "Coeliac disease"),

        // Skin
        new("L70.0", "آکنه (جوش)", "Acne vulgaris"),
        new("L20.9", "اگزمای آتوپیک", "Atopic dermatitis, unspecified"),
        new("L30.9", "درماتیت (اگزما)", "Dermatitis, unspecified"),
        new("L40.0", "پسوریازیس", "Psoriasis vulgaris"),
        new("L50.9", "کهیر", "Urticaria, unspecified"),
        new("L63.9", "ریزش موی سکه‌ای (آلوپسی آره‌آتا)", "Alopecia areata, unspecified"),
        new("L64.9", "ریزش موی آندروژنیک", "Androgenic alopecia, unspecified"),
        new("L65.9", "ریزش مو", "Nonscarring hair loss, unspecified"),
        new("L80", "ویتیلیگو (پیسی)", "Vitiligo"),
        new("L81.1", "ملاسما (کک و مک بارداری)", "Chloasma (melasma)"),
        new("L71.9", "روزاسه", "Rosacea, unspecified"),
        new("L21.9", "درماتیت سبورئیک (شوره)", "Seborrhoeic dermatitis, unspecified"),
        new("L68.0", "پرمویی (هیرسوتیسم)", "Hirsutism"),
        new("L90.6", "ترک پوستی (استریا)", "Striae atrophicae"),
        new("L29.9", "خارش", "Pruritus, unspecified"),
        new("L74.1", "تعریق زیاد (هیپرهیدروز)", "Hyperhidrosis"),
        new("B00.1", "تبخال", "Herpesviral vesicular dermatitis (cold sore)"),
        new("B02.9", "زونا", "Zoster without complication"),
        new("B02.2", "درد عصبی پس از زونا", "Zoster with other nervous system involvement (postherpetic neuralgia)"),
        new("B07", "زگیل", "Viral warts"),
        new("B35.1", "قارچ ناخن", "Tinea unguium"),
        new("L91.0", "اسکار هیپرتروفیک (کلوئید)", "Hypertrophic scar (keloid)"),

        // Musculoskeletal
        new("M54.5", "کمردرد", "Low back pain"),
        new("M54.2", "گردن‌درد", "Cervicalgia"),
        new("M54.3", "سیاتیک", "Sciatica"),
        new("M54.4", "کمردرد همراه سیاتیک", "Lumbago with sciatica"),
        new("M54.6", "درد ناحیه پشت (توراسیک)", "Pain in thoracic spine"),
        new("M54.9", "درد پشت، نامشخص", "Dorsalgia, unspecified"),
        new("M51.1", "دیسک کمر با درگیری ریشه عصب", "Lumbar and other intervertebral disc disorders with radiculopathy"),
        new("M51.2", "بیرون‌زدگی دیسک کمر", "Other specified intervertebral disc displacement"),
        new("M50.1", "دیسک گردن با درگیری ریشه عصب", "Cervical disc disorder with radiculopathy"),
        new("M47.8", "آرتروز ستون فقرات (اسپوندیلوز)", "Other spondylosis"),
        new("M48.0", "تنگی کانال نخاع", "Spinal stenosis"),
        new("M43.1", "لغزش مهره (اسپوندیلولیستزیس)", "Spondylolisthesis"),
        new("M41.9", "اسکولیوز", "Scoliosis, unspecified"),
        new("M53.1", "سندرم گردن-شانه", "Cervicobrachial syndrome"),
        new("M75.0", "شانه یخ‌زده (کپسولیت چسبنده)", "Adhesive capsulitis of shoulder"),
        new("M75.1", "پارگی یا آسیب روتاتور کاف", "Rotator cuff syndrome"),
        new("M75.4", "سندرم گیرافتادگی شانه", "Impingement syndrome of shoulder"),
        new("M25.51", "درد شانه", "Pain in joint, shoulder region"),
        new("M77.1", "آرنج تنیس‌بازان", "Lateral epicondylitis (tennis elbow)"),
        new("M77.0", "آرنج گلف‌بازان", "Medial epicondylitis (golfer's elbow)"),
        new("M65.3", "انگشت ماشه‌ای", "Trigger finger"),
        new("M65.4", "تنوسینوویت دوکرون", "Radial styloid tenosynovitis (de Quervain)"),
        new("M17.9", "آرتروز زانو", "Gonarthrosis, unspecified"),
        new("M16.9", "آرتروز لگن", "Coxarthrosis, unspecified"),
        new("M19.9", "آرتروز (استئوآرتریت)", "Arthrosis, unspecified"),
        new("M15.9", "آرتروز منتشر", "Polyarthrosis, unspecified"),
        new("M25.56", "درد زانو", "Pain in joint, lower leg (knee)"),
        new("M22.4", "نرمی کشکک زانو", "Chondromalacia patellae"),
        new("M76.6", "تاندونیت آشیل", "Achilles tendinitis"),
        new("M72.2", "خار پاشنه (فاشئیت کف پایی)", "Plantar fascial fibromatosis (plantar fasciitis)"),
        new("M77.3", "خار پاشنه", "Calcaneal spur"),
        new("M79.7", "فیبرومیالژیا", "Fibromyalgia"),
        new("M79.1", "درد عضلانی", "Myalgia"),
        new("M62.8", "گرفتگی و اسپاسم عضلانی", "Other specified disorders of muscle (muscle spasm)"),
        new("M79.6", "درد اندام", "Pain in limb"),
        new("M25.5", "درد مفصل", "Pain in joint"),
        new("M06.9", "آرتریت روماتوئید", "Rheumatoid arthritis, unspecified"),
        new("M10.9", "نقرس", "Gout, unspecified"),
        new("M45", "اسپوندیلیت آنکیلوزان", "Ankylosing spondylitis"),
        new("M32.9", "لوپوس", "Systemic lupus erythematosus, unspecified"),
        new("M81.9", "پوکی استخوان", "Osteoporosis, unspecified"),
        new("M85.8", "کاهش تراکم استخوان (استئوپنی)", "Other specified disorders of bone density and structure (osteopenia)"),
        new("M70.6", "بورسیت لگن (تروکانتر)", "Trochanteric bursitis"),
        new("M53.3", "درد دنبالچه", "Sacrococcygeal disorders (coccygodynia)"),
        new("M46.1", "التهاب مفصل ساکروایلیاک", "Sacroiliitis"),
        new("M60.8", "سندرم پیریفورمیس و سایر میوزیت‌ها", "Other myositis (piriformis syndrome)"),
        new("S13.4", "پیچ‌خوردگی گردن (ضربه شلاقی)", "Sprain and strain of cervical spine (whiplash)"),
        new("S33.5", "رگ‌به‌رگ شدن کمر", "Sprain and strain of lumbar spine"),
        new("S93.4", "پیچ‌خوردگی مچ پا", "Sprain and strain of ankle"),
        new("S83.6", "آسیب رباط زانو", "Sprain and strain of other parts of knee"),

        // Genitourinary
        new("N94.6", "قاعدگی دردناک (دیسمنوره)", "Dysmenorrhoea, unspecified"),
        new("N94.3", "سندرم پیش از قاعدگی", "Premenstrual tension syndrome"),
        new("N92.6", "قاعدگی نامنظم", "Irregular menstruation, unspecified"),
        new("N92.0", "خونریزی زیاد قاعدگی", "Excessive and frequent menstruation with regular cycle"),
        new("N91.2", "قطع قاعدگی (آمنوره)", "Amenorrhoea, unspecified"),
        new("N95.1", "یائسگی و عوارض آن", "Menopausal and female climacteric states"),
        new("N97.9", "ناباروری زنان", "Female infertility, unspecified"),
        new("N46", "ناباروری مردان", "Male infertility"),
        new("N80.9", "اندومتریوز", "Endometriosis, unspecified"),
        new("D25.9", "فیبروم رحم (میوم)", "Leiomyoma of uterus, unspecified"),
        new("N60.1", "بیماری فیبروکیستیک پستان", "Diffuse cystic mastopathy"),
        new("N64.4", "درد پستان (ماستودینی)", "Mastodynia"),
        new("N76.0", "واژینیت", "Acute vaginitis"),
        new("N39.0", "عفونت ادراری", "Urinary tract infection, site not specified"),
        new("N30.9", "التهاب مثانه (سیستیت)", "Cystitis, unspecified"),
        new("N39.3", "بی‌اختیاری ادرار استرسی", "Stress incontinence"),
        new("R32", "بی‌اختیاری ادرار", "Unspecified urinary incontinence"),
        new("N32.8", "مثانه بیش‌فعال", "Other specified disorders of bladder (overactive bladder)"),
        new("N20.0", "سنگ کلیه", "Calculus of kidney"),
        new("N40", "بزرگی خوش‌خیم پروستات", "Hyperplasia of prostate"),
        new("N41.1", "التهاب مزمن پروستات", "Chronic prostatitis"),
        new("N48.4", "ناتوانی جنسی با علت عضوی", "Impotence of organic origin"),
        new("N18.9", "بیماری مزمن کلیه", "Chronic kidney disease, unspecified"),
        new("R35", "تکرر ادرار شبانه و روزانه", "Polyuria (frequency)"),
        new("N39.4", "شب‌ادراری و سایر بی‌اختیاری‌ها", "Other specified urinary incontinence"),

        // Pregnancy
        new("O21.0", "تهوع و استفراغ بارداری", "Mild hyperemesis gravidarum"),
        new("O26.8", "سایر مشکلات بارداری (کمردرد بارداری)", "Other specified pregnancy-related conditions"),
        new("Z32.1", "بارداری تأییدشده", "Pregnancy confirmed"),
        new("O92.7", "مشکلات شیردهی", "Other and unspecified disorders of lactation"),

        // Symptoms
        new("R53", "خستگی و ضعف", "Malaise and fatigue"),
        new("G93.3", "سندرم خستگی مزمن", "Postviral fatigue syndrome (chronic fatigue syndrome)"),
        new("R52.2", "درد مزمن", "Other chronic pain"),
        new("R52.9", "درد، نامشخص", "Pain, unspecified"),
        new("R07.4", "درد قفسه سینه", "Chest pain, unspecified"),
        new("R50.9", "تب", "Fever, unspecified"),
        new("R61", "تعریق زیاد", "Hyperhidrosis, generalized"),
        new("R20.2", "گزگز و مورمور (پارستزی)", "Paraesthesia of skin"),
        new("R25.2", "کرامپ و گرفتگی عضله", "Cramp and spasm"),
        new("R23.2", "گرگرفتگی", "Flushing"),
        new("R45.0", "عصبی بودن", "Nervousness"),
        new("R45.4", "تحریک‌پذیری و خشم", "Irritability and anger"),
        new("R41.3", "فراموشی", "Other amnesia"),
        new("R43.0", "از دست دادن حس بویایی", "Anosmia"),
        new("R68.2", "خشکی دهان", "Dry mouth, unspecified"),
        new("R12", "سوزش سر دل", "Heartburn"),
        new("R19.7", "اسهال", "Diarrhoea, unspecified"),

        // Factors influencing health
        new("Z72.0", "مصرف دخانیات (سیگار)", "Tobacco use"),
        new("Z71.3", "مشاوره و پایش رژیم غذایی", "Dietary counselling and surveillance"),
        new("Z73.0", "فرسودگی شغلی", "Burn-out"),
        new("Z73.3", "استرس", "Stress, not elsewhere classified"),
        new("Z00.0", "معاینه عمومی سلامت", "General medical examination"),
        new("Z51.8", "مراقبت پزشکی دیگر (درمان تکمیلی)", "Other specified medical care"),
        new("Z50.1", "سایر درمان‌های فیزیکی", "Other physical therapy"),
        new("Z98.8", "وضعیت پس از جراحی", "Other specified postsurgical states"),
        new("Z86.7", "سابقه بیماری قلبی-عروقی", "Personal history of diseases of the circulatory system"),
    ];

    private static readonly Dictionary<string, Icd10Code> ByCode = All
        .GroupBy(c => c.Code)
        .ToDictionary(g => g.Key, g => g.First(), StringComparer.OrdinalIgnoreCase);

    public static Icd10Code? Find(string? code) =>
        code is not null && ByCode.TryGetValue(code.Trim(), out var found) ? found : null;
}
