"""Generates the point charts and the point library.

    python3 tools/charts/generate.py          # photo charts when photo/silhouettes.json exists (see photo.py)
    python3 tools/charts/generate.py --drawn  # the drawn charts, on purpose

Writes src/Clinic.Web/wwwroot/img/charts/<view>.svg and
src/Clinic.Application/Acupuncture/AcupointLibrary.Data.g.cs. Edit figures.py (drawings) or points.py
(points, placements, protocols) and run it again; never edit the generated files by hand.
"""
import hashlib
import os
import sys

import photo
from figures import VIEWS as FIGURES
from points import POINTS as DRAWN_POINTS, PROTOCOLS, VIEWS

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
CHARTS = os.path.join(ROOT, "src", "Clinic.Web", "wwwroot", "img", "charts")
DATA = os.path.join(ROOT, "src", "Clinic.Application", "Acupuncture", "AcupointLibrary.Data.g.cs")


def num(v):
    s = f"{float(v):.1f}"
    return s[:-2] if s.endswith(".0") else s


def cs(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


DRAWN = "--drawn" in sys.argv  # go back to the drawn charts on purpose
PHOTO = photo.available() and not DRAWN
PHOTO_VIEWS = set(photo.VIEWS) if PHOTO else set()
if not PHOTO and not DRAWN:
    left = [k for k in photo.VIEWS if os.path.exists(os.path.join(CHARTS, f"{k}.png"))]
    if left:
        sys.exit("The rendered photo charts are in use (" + ", ".join(left[:3]) + "...) but tools/charts/photo/silhouettes.json "
                 "or tools/blender/charts.json is missing, so the charts would silently fall back to the drawings. Restore the "
                 "file (python3 tools/charts/silhouettes.py rebuilds the silhouettes from the PNGs), or pass --drawn to go back "
                 "to the drawings on purpose.")


def placed(points):
    """The points with their positions on the charts as shown: moved onto the photo charts when those are in use.
    A placement that lands outside its photo chart (the chart frame is cut lower than the drawing was) is left off that
    chart; the point stays on its other charts."""
    if not PHOTO:
        return points
    sizes = {v: FIGURES[v][:2] for v in PHOTO_VIEWS}
    symmetric = {v[0]: v[2] for v in VIEWS}
    out, dropped = [], []
    for code, name, meridian, views in points:
        moved = {}
        for v, (x, y) in views.items():
            if v not in PHOTO_VIEWS:
                moved[v] = (x, y)
                continue
            nx, ny = photo.remap(v, x, y, code)
            w, h = sizes[v]
            if 0 <= ny <= h and 0 <= nx <= (w / 2 if symmetric[v] else w):
                moved[v] = (nx, ny)
            else:
                dropped.append(f"{code} on {v}")
        assert moved, f"{code} would be on no chart"
        out.append((code, name, meridian, moved))
    if dropped:
        print("Left off the photo charts (outside the frame):", ", ".join(dropped))
    return out


POINTS = placed(DRAWN_POINTS)


def photo_files():
    for key in sorted(PHOTO_VIEWS):
        path = os.path.join(CHARTS, f"{key}.png")
        assert os.path.exists(path), f"{path} is missing: copy the rendered charts into wwwroot/img/charts"
        yield path


def check():
    keys = {v[0] for v in VIEWS}
    assert keys == set(FIGURES), "points.py and figures.py list different views"
    codes = [p[0] for p in POINTS]
    dupes = {c for c in codes if codes.count(c) > 1}
    assert not dupes, f"duplicate codes: {dupes}"
    for code, _, _, views in POINTS:
        assert views, f"{code} is on no chart"
        for view, (x, y) in views.items():
            w, h, _ = FIGURES[view]
            symmetric = next(v[2] for v in VIEWS if v[0] == view)
            assert 0 <= y <= h, f"{code} on {view}: y {y} is off the chart"
            assert (0 <= x <= w / 2) if symmetric else (0 <= x <= w), f"{code} on {view}: x {x} is off the chart"
    for key, _, protocol in PROTOCOLS:
        missing = [c for c in protocol if c not in codes]
        assert not missing, f"protocol {key} uses unknown points {missing}"


def main():
    check()
    os.makedirs(CHARTS, exist_ok=True)
    digest = hashlib.sha256()
    for key, (w, h, draw) in FIGURES.items():
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}">'
               f"<!-- Generated by tools/charts/generate.py -->{draw()}</svg>\n")
        digest.update(svg.encode())
        with open(os.path.join(CHARTS, f"{key}.svg"), "w", encoding="utf-8") as f:
            f.write(svg)
    for path in photo_files():
        with open(path, "rb") as f:
            digest.update(f.read())

    symmetric = {v[0]: v[2] for v in VIEWS}
    lines = [
        "// <auto-generated>Generated by tools/charts/generate.py from tools/charts/points.py. Do not edit.</auto-generated>",
        "namespace Clinic.Application.Acupuncture;",
        "",
        "public static partial class AcupointLibrary",
        "{",
        f"    /// <summary>Changes whenever a chart drawing changes, so browsers fetch the new images.</summary>",
        f"    public const string ChartsVersion = {cs(digest.hexdigest()[:10])};",
        "",
        "    private static readonly ChartView[] ViewData =",
        "    [",
    ]
    for key, page, sym, faces in VIEWS:
        w, h, _ = FIGURES[key]
        ext = ', "png"' if key in PHOTO_VIEWS else ""
        lines.append(f"        new({cs(key)}, {cs(page)}, {w}, {h}, {str(sym).lower()}, {str(faces).lower()}{ext}),")
    lines += ["    ];", "", "    private static readonly Acupoint[] PointData =", "    ["]
    for code, name, meridian, views in POINTS:
        sym_views = [xy for v, xy in views.items() if symmetric[v]]
        midline = meridian in ("GV", "CV") or (bool(sym_views) and all(x == 0 for x, _ in sym_views))
        places = ", ".join(f"new({cs(v)}, {num(x)}, {num(y)})" for v, (x, y) in views.items())
        lines.append(f"        new({cs(code)}, {cs(name)}, {cs(meridian)}, {str(midline).lower()}, [{places}]),")
    lines += ["    ];", "", "    private static readonly Protocol[] ProtocolData =", "    ["]
    for key, name, codes in PROTOCOLS:
        lines.append(f"        new({cs(key)}, {cs(name)}, [{', '.join(cs(c) for c in codes)}]),")
    lines += ["    ];", "}", ""]
    with open(DATA, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"{len(FIGURES)} charts ({len(PHOTO_VIEWS)} from photos), {len(POINTS)} points, {len(PROTOCOLS)} protocols")


if __name__ == "__main__":
    main()
